### ISSUE TITLE
construction problem

### ISSUE THREAD

**Issue by crazyrayLing** [aprilbian/ST_JSCC#1]
hello，dear author！
i wanna ask that compare with the paper, your code seems to have an extra CA module and Resnet module. how to explain it!

**Comment by aprilbian** [comment]
Thanks for the question, actually, I remember by experiments that having one more CA module and Resnet module does not improve the performance, so I just keep what it is in the paper. I think you can verify it by yourself.

**Comment by crazyrayLing** [comment]
@aprilbian thanks for your replay.
